### ISSUE TITLE
[Discord/NesVi] Feature Suggestions

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.19#2]
_**Changing the cocoa drop, now instead of getting cocoa seed/beans, you get the fruit itself, so you have to treat and/or toast the fruit to actually get cocoa seeds you can use for cooking. Obviously, for encouraging players to elaborate cocoa, it would be precise to add many cocoa recipes like chocolate cake, hot cocoa, better cookies...**_ 

I try not to mess around too much with the Core functionality as that we label us as a "Core" mod and it could mess with other mods. We could make our own Cocoa tree and implement this.

**_GC has rice, lets make it more useful! Every country has its own way to cook it, paella, cuban rice, three delights, rice balls... we can even add a great "paellera" where you can cook a lot of rice and put it on plates by rigth clicking it._**

This is doable and within scope.

**_Generate Fast Food Restaurants on villages where you can buy/sell food to a villager with a new job, the Chef._**

Already have plans for food vendors.

**_Add mead as a new alcoholic drink._**

Mead has been in since 1.710, used to be called Growthcraft Bees and has been in Growthcraft Apiary since 1.16

**_Animals would drop extra food pieces, like, bacon, pork leg (for ham), ribs... This will give more freedom to create new recipes with specific animal cuts. We also can add mechanics were we need to feed our animals well to get specific kinds of meat from our animals (like feeding only acorn to pigs will let you get his leg for curing and making the famous spanish acorn ham)_**

Affects core functionality. Instead we could make custom meets from "beef", "lamb chop", etc using the Stone Cutter.

_**Using the kettle and/or vanilla cauldron for cooking (rice, ferments)**_

Rice is currently cooked in the Brew Kettle, have to use the lid to steam it.

_**Add a mechanic to make you able to harvest flowers similar to the way we plant and harvest crops.**_

Thistle does this now. We could spread to non-vanilla floors.

**_BUTTER. COOKIES. who doesnt like denmark butter cookies?_**

Cookies is planned for Growthcraft Confectionary

**_Add a fryer where you can fry meat, potatoes, fish, your noisy neighbor... this could be a block with a GUI similar to the furnace that can be powered by coal/electrical energy(you´ll need olive/sunflower oil)_**

Doable and within scope. Would be able to add oil sources as well.

**_More fruit trees and bushes._**

Doable as long as the produce has a purpose.

**_A health bar and a happiness bar you need to balance by eating different food to be sane and alive(?)._**

Out of scope for GC, we do not mess with the HUD.

**_Every update has its own name, like: the "insert country" update._**

Can look into this in the future once the porting is stable. Although would likely lean towards naming the updates based on the focus of the update which would likely not be country focused. (like Growthcraft 1.7.10 Cheese Update, as it added cheeses)

**Comment by NesVicOC** [comment]
*About cocoa: 
For avoiding messing with the core, its better to let the drop being just cocoa beans, but putting them on the furnace would lead to get cooked cocoa beans, that the player would have to crush (maybe using the fruit press so the coding of a new GUI block isnt needed?) for getting cocoa powder, the one new recipes could use to make every new chocolate-related food.

*The fruit press (or a new GUI block called crusher) can be used aswell to make flour and crushing items to make spices (paprika for example). This would open a lot of opportunities for new recipes while keeping the realistic and funny GC style to create things by doing multiple steps.

*Adding soft cheese, a variety of cheese with little to no cure time, very healthy and interesting to eat with honey, jam and other sweet flavors, also perfect for elaborating sandwiches [A wiki about this cheese, didnt found anything in english](https://es.wikipedia.org/wiki/Queso_fresco).

*Some cheese manufacturers use paprika to cover cheese wheels instead of wax.

*Contacting the Diet mod authors to add compatibility with this two mods, since GC food expansion would fit perfectly with this mod and the compatibility will only be some archive they have that adds some new variables to food, if I remember well.

**Comment by CastorF1ber** [comment]
I would like to suggest a bottle label. With it you could rename "Bottle of red wine" to the name of your "wine yard". Of course you can do this using a anvil but it's expensive. And with label you could either the type and the name of your wine
