### ISSUE TITLE
Milking bucket returns as Bucket after using

### ISSUE THREAD

**Issue by CastorF1ber** [GrowthcraftCE/Growthcraft-1.19#44]
This bug is still happening to me. When you put milk from Milk Bucket (from GC), the game returns you empty minecraft bucket, so you cannot use it any more in GC recipes.

**Comment by Alatyami** [comment]
This is somewhat resolved in the next build. The issue with "buckets" is that it is hard coded that a Items.BUCKET is returned. In order to override this we would have to implement our own bucket. As a resolution, when picking up a GrowthcraftMilk fluid, the standard bucket converts to a milking bucket. Standard buckets can already get milk from cows so the Iron Milking Bucket really no longer has a purpose other than what the item model looks like.
