### ISSUE TITLE
[1.19.4]

### ISSUE THREAD

**Issue by futill** [GrowthcraftCE/Growthcraft-1.19#98]
Why is it not directly right-clicked to open the GUI in version 1.19.4 but to shift empty clicked?

**Comment by Alatyami** [comment]
Historically our "machine" blocks were very interactive with what the player has in their hand so that if a Server instance wanted to, they could disable the GUI for the blocks. We are moving away from that level of interaction and likely in the next few releases, you will be interacting with the blocks by simply right click activating when you do not have  a bucket or item container in your hand.

Feel free to jump on our Discord server for more questions and answers.

https://discord.gg/bnqBfywp
